package com.example.settings

object Loc {
    private val translations = mapOf(
        "en" to mapOf(
            "app_title" to "SIM Monitor",
            "app_subtitle" to "Keep-Alive & Consumption Manager",
            "connectivity_manager" to "CONNECTIVITY MANAGER",
            "recent_sims" to "RECENT SIMS",
            "active_cards" to "Active Cards",
            "at_risk" to "At Risk",
            "view_all" to "View All",
            "no_sim_recorded" to "No SIM cards recorded",
            "add_first_card_prompt" to "Tap the button below or top right to add your first card.",
            "reminder_set" to "Reminder Set",
            "reminder_set_desc" to "A local keep-alive notification alert has been scheduled for %s.",
            "search_placeholder" to "Search SIMs...",
            
            "rules_title" to "Carrier Rules",
            "rules_subtitle" to "RULE PRESETS",
            "rules_desc" to "Default rules based on carrier requirements...",
            "builtin" to "Built-In",
            "custom" to "Custom",
            "duplicate" to "Duplicate",
            "edit" to "Edit",
            "delete" to "Delete",
            "create_custom_rule" to "Create Custom Rule",
            "edit_custom_rule" to "Edit Custom Rule",
            "rule_name" to "Rule Name",
            "rule_name_hint" to "e.g., Giffgaff Keep-alive",
            "carrier_name" to "Network Operator / Carrier",
            "carrier_name_hint" to "e.g., Giffgaff",
            "target_country" to "Target Country",
            "target_country_hint" to "e.g., UK",
            "active_period" to "Active Validity Period (Days)",
            "active_period_desc" to "Interval between required actions (e.g. 180 days)",
            "first_warning" to "First Notification Warning",
            "first_warning_desc" to "Days before expiry to send first alert",
            "second_warning" to "Second Notification Warning",
            "second_warning_desc" to "Days before expiry to send second alert",
            "final_warning" to "Final Action Threshold",
            "final_warning_desc" to "Days before expiry to trigger high risk mode",
            "keep_alive_actions" to "Required Keep-Alive Actions",
            "send_sms" to "Send SMS",
            "make_call" to "Make Call",
            "mobile_data" to "Mobile Data Use",
            "top_up" to "Top-Up / Recharge",
            "min_spend" to "Min Spend Value",
            "min_spend_desc" to "Optional local spend required to keep alive",
            "has_activation_rule" to "Has Card Activation Keep-Alive Rule",
            "has_activation_rule_desc" to "Requires specific action within N days of activation",
            "activation_deadline" to "First Action Deadline (Days)",
            "activation_deadline_hint" to "e.g., 90",
            "allow_keep_alive" to "Allow Paid Auto-Keep-Alive Service",
            "allow_keep_alive_desc" to "Carrier officially supports paid automatic renewal",
            "keep_alive_desc_field" to "Paid Service Description",
            "keep_alive_desc_hint" to "e.g., £5 auto top-up credit every 3 months",
            "create_new_rule_preset" to "Create New Rule Preset",
            "save_changes" to "Save Changes",

            "add_sim_title" to "Add SIM Card",
            "edit_sim_title" to "Edit SIM Card",
            "card_label" to "Card Label / Alias",
            "card_label_hint" to "e.g., My UK Primary",
            "phone_number" to "Phone Number",
            "phone_number_hint" to "e.g., +44 7512 345678",
            "iccid" to "SIM Card Physical ICCID",
            "iccid_hint" to "Optional unique 19-20 digit serial number",
            "select_rule" to "Select Expiration & Alert Rule Protocol",
            "last_action_date" to "Last Action Date / Simulated Active Period Start",
            "activation_date" to "Initial Card Activation Date",
            "preferred_country" to "Preferred Country Group",
            "additional_desc" to "Additional Description / ICCID notes",
            
            "user_preferences" to "USER PREFERENCES",
            "settings" to "Settings",
            "notifications_automation" to "NOTIFICATIONS & AUTOMATION",
            "enable_local_alerts" to "Enable Local Alerts",
            "enable_local_alerts_desc" to "Show calendar warnings when expiration dates draw near",
            "daily_expiry_inspector" to "Daily Expiry Inspector",
            "daily_expiry_inspector_desc" to "Run daily checks of all cards in the background",
            "inspect_start_time" to "Inspect Start Time",
            "visuals_safety" to "VISUALS & DATA SAFETY",
            "dynamic_dark_mode" to "Dynamic Dark Mode",
            "dynamic_dark_mode_desc" to "Switch application background colors to dim-eye mode",
            "obscure_phone" to "Obscure Phone Digits",
            "obscure_phone_desc" to "Mask middle digits of list items (+44 75****20)",
            "language_setting" to "App Language",
            "default_protocols" to "DEFAULT PROTOCOLS",
            "default_country" to "Default Country",
            "default_currency" to "Default Currency",
            "backups_resets" to "BACKUPS & RESETS",
            "export_backup" to "Export local JSON backups",
            "export_backup_desc" to "Serialize SIM states and save details offline",
            "import_backup" to "Import JSON file",
            "import_backup_desc" to "Read and parse backup sheets to restore profile",
            "reset_database" to "Reset database completely",
            "reset_database_desc" to "Wipe all records and reload vanilla configurations",
            "factory_reset_title" to "Factory Reset Database",
            "factory_reset_desc" to "Are you absolutely sure you want to clean SIM Monitor? Doing so wipes out all logs, SIM cards, notifications, and resets rules to baseline defaults.",
            "reset_everything" to "Reset Everything",
            "cancel" to "Cancel",
            "import_profile_title" to "Import Backup Profile",
            "import_profile_desc" to "This handles reading our automated SIM Monitor backup schema from your offline folder and restores your 4 simulation cards instantly.",
            "import_backup_data_btn" to "Import Backup Data",
            "json_exported_title" to "JSON Backup Exported",
            "json_exported_desc" to "SIM Monitor successfully serialized all your SIM cards and local history logs into a backup schema inside /storage/emulated/0/Documents/sim_monitor_backup.json.",
            "success" to "Success",
            "db_wiped_msg" to "Database tables wiped successfully",
            "backup_imported_msg" to "JSON Backup cards imported successfully",
            
            "sim_profile" to "SIM Card Profile",
            "physical_metadata" to "Physical SIM Card Metadata",
            "carrier_profile" to "Carrier Profile",
            "current_status" to "Current Card Status",
            "last_action_taken" to "Last Action Taken",
            "next_keep_alive" to "Next Keep-Alive Action Due",
            "cycle_remaining" to "Cycle Time Remaining",
            "trigger_action_title" to "Trigger Keep-Alive Action SIM",
            "actions_executed" to "Actions Executed",
            "trigger_action_btn" to "Trigger Action",
            "delete_sim_btn" to "Delete SIM Card",
            
            "sim_auto_checks" to "SIM AUTO CHECKS",
            "inspection_history" to "Inspection History",
            "history_desc" to "View background scan history...",
            "clear_all_logs" to "Clear All Logs",
            "no_logs" to "No logs recorded yet"
        ),
        "zh" to mapOf(
            "app_title" to "SIM 保号管家",
            "app_subtitle" to "多卡保号与预警助手",
            "connectivity_manager" to "我的卡包总览",
            "recent_sims" to "电话卡列表",
            "active_cards" to "健康在网",
            "at_risk" to "风险预警",
            "view_all" to "查看全部",
            "no_sim_recorded" to "暂未添加任何电话卡",
            "add_first_card_prompt" to "点击右上角或下方按钮添加您的首张卡片",
            "reminder_set" to "提醒已设置",
            "reminder_set_desc" to "已为 %s 安排本地保号通知提醒。",
            "search_placeholder" to "搜索 SIM 卡...",
            
            "rules_title" to "运营商规则",
            "rules_subtitle" to "规则预设",
            "rules_desc" to "基于运营商要求的预设保号触发规则",
            "builtin" to "内置",
            "custom" to "自定义",
            "duplicate" to "克隆",
            "edit" to "编辑",
            "delete" to "删除",
            "create_custom_rule" to "创建自定义规则",
            "edit_custom_rule" to "编辑自定义规则",
            "rule_name" to "规则名称",
            "rule_name_hint" to "例如：Giffgaff 常规保号",
            "carrier_name" to "运营商名称",
            "carrier_name_hint" to "例如：Giffgaff",
            "target_country" to "目标国家/地区",
            "target_country_hint" to "例如：英国",
            "active_period" to "最大有效周期 (天)",
            "active_period_desc" to "两次保号操作之间的最长周期间隔 (如 180 天)",
            "first_warning" to "首次到期预警",
            "first_warning_desc" to "过期前多少天发送首次预警",
            "second_warning" to "二次通知预警",
            "second_warning_desc" to "过期前多少天发送二次预警",
            "final_warning" to "最后动作临界天数",
            "final_warning_desc" to "过期前多少天触发高风险模式",
            "keep_alive_actions" to "所需的保号动作",
            "send_sms" to "发送短信",
            "make_call" to "拨打电话",
            "mobile_data" to "产生流量消耗",
            "top_up" to "充值话费/购买套餐",
            "min_spend" to "最低消费金额",
            "min_spend_desc" to "保持活跃状态所需的最低本地消费金额",
            "has_activation_rule" to "包含首激活保号规则",
            "has_activation_rule_desc" to "激活后是否须在特定天数内完成首保",
            "activation_deadline" to "首保期限 (天)",
            "activation_deadline_hint" to "例如：90",
            "allow_keep_alive" to "允许付费保号托管服务",
            "allow_keep_alive_desc" to "运营商官方是否支持付费自动保号",
            "keep_alive_desc_field" to "付费服务说明",
            "keep_alive_desc_hint" to "例如：每 3 个月自动充值 5 英镑余额",
            "create_new_rule_preset" to "创建全新规则预设",
            "save_changes" to "保存修改",

            "add_sim_title" to "添加 SIM 卡",
            "edit_sim_title" to "编辑 SIM 卡",
            "card_label" to "卡片标签 / 别名",
            "card_label_hint" to "例如：我的英国主卡",
            "phone_number" to "手机号码",
            "phone_number_hint" to "例如：+44 7512 345678",
            "iccid" to "SIM卡物理卡号 ICCID",
            "iccid_hint" to "可选的 19-20 位唯一序列号",
            "select_rule" to "选择保号/提醒规则协议",
            "last_action_date" to "上次保号动作日期 / 周期开始日",
            "activation_date" to "卡片开卡激活日期",
            "preferred_country" to "首选国家/地区",
            "additional_desc" to "附加备注 / 额外说明",
            
            "user_preferences" to "用户偏好",
            "settings" to "设置",
            "notifications_automation" to "通知与自动化",
            "enable_local_alerts" to "启用本地警报",
            "enable_local_alerts_desc" to "到期日临近时显示日历式警告",
            "daily_expiry_inspector" to "每日到期自检",
            "daily_expiry_inspector_desc" to "在后台每天检查所有卡的状态",
            "inspect_start_time" to "自检启动时间",
            "visuals_safety" to "界面与数据安全",
            "dynamic_dark_mode" to "极简深色模式",
            "dynamic_dark_mode_desc" to "切换应用背景为护眼夜间色调",
            "obscure_phone" to "部分遮显手机号",
            "obscure_phone_desc" to "遮蔽列表中间数位以防隐私泄露 (+44 75****20)",
            "language_setting" to "应用语言",
            "default_protocols" to "默认协议参数",
            "default_country" to "默认国家地区",
            "default_currency" to "默认货币",
            "backups_resets" to "备份与重置",
            "export_backup" to "导出本地 JSON 备份",
            "export_backup_desc" to "将 SIM 卡状态序列号序列化存储于离线文档",
            "import_backup" to "导入 JSON 备份",
            "import_backup_desc" to "读取并解析本地备份文档以恢复账户",
            "reset_database" to "重置并清除全部数据库",
            "reset_database_desc" to "清除全部记录并恢复纯净出厂配置",
            "factory_reset_title" to "还原出厂数据库",
            "factory_reset_desc" to "您确定要清空 SIM Monitor 吗？这将抹除所有账单、SIM卡、保号记录，并将规则恢复到初始状态。",
            "reset_everything" to "重置所有",
            "cancel" to "取消",
            "import_profile_title" to "导入备份档案",
            "import_profile_desc" to "从手机本地读取备份文件，并一键恢复所有卡片配置及日志记录。",
            "import_backup_data_btn" to "导入备份",
            "json_exported_title" to "JSON 备份已导出",
            "json_exported_desc" to "SIM Monitor 已将您所有的 SIM 卡与历史自检日志成功导出到文件 /storage/emulated/0/Documents/sim_monitor_backup.json 中。",
            "success" to "成功",
            "db_wiped_msg" to "数据库表已成功抹除",
            "backup_imported_msg" to "JSON 备份已成功导入",
            
            "sim_profile" to "SIM卡详情",
            "physical_metadata" to "物理 SIM 卡元数据",
            "carrier_profile" to "运营商属性",
            "current_status" to "卡片状态",
            "last_action_taken" to "上次保号动作",
            "next_keep_alive" to "下次需保号时间",
            "cycle_remaining" to "余天保号倒计时",
            "trigger_action_title" to "触发 SIM 卡保号操作",
            "actions_executed" to "保号动作日志",
            "trigger_action_btn" to "直接触发保号动作",
            "delete_sim_btn" to "删除 SIM 卡",
            
            "sim_auto_checks" to "系统状态自检日志",
            "inspection_history" to "自检与保号日志",
            "history_desc" to "查看系统后台巡检以及手动触发的保号历史...",
            "clear_all_logs" to "清空全部日志",
            "no_logs" to "当前暂无保号日志记录"
        )
    )

    fun t(key: String, lang: String): String {
        val dict = translations[lang] ?: translations["en"]!!
        return dict[key] ?: translations["en"]!![key] ?: key
    }
}
